ToDo list structure
hiwina/ToDo-List-App pull request #1
Opened 2023-05-04 22:31 UTC by hiwina

- [ ] Setup webpack for the project
- [ ] Add index.html, index.js and index.css
- [ ] Configured linters

2023-05-04 23:45 UTC, andersonlebon reviewed
## Hi  @hiwina 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional Readme file kindly follow this [microverse template](https://github.com/microverseinc/readme-template) and work on your README file the request another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-05 07:43 UTC, VICTOR-CHUKWU requested changes
Hi @hiwina  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 07:43 UTC, VICTOR-CHUKWU commented on package.json
> +    "build": "webpack"
- [ ] kindly include a command to run your webpack in dev mode e.g `"serve": "webpack serve --open "`

2023-05-05 07:43 UTC, VICTOR-CHUKWU commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] your MIT license link is broken, kindly fix

2023-05-05 09:35 UTC, uwadonat approved these changes
## Hi @hiwina,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Well organized and clean project ✔️
- Professional readme file ✔️
- Good commit messages ✔️
![thanks-awesome](https://user-images.githubusercontent.com/65860678/236424258-55cd2e8b-b383-42d1-8614-f5aa7bc1592d.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-05 09:36 UTC, merged